build-and-test:
  runs-on: ubuntu-latest  # Adjust runner OS if needed for your project
  steps:
    - uses: actions/checkout@v3
    # Check for folder existence (indented under the job)
    name: Check for folder existence
    run: |
      if [ -d "Playwright_API_Automation" ]; then
        echo "Folder found, proceeding with steps"
      else
        echo "Folder not found, skipping steps"
        exit 0
      fi
    # Install dependencies (indented under the job)
    name: Install dependencies (if folder exists)
    if: steps.check-for-folder.outputs == 'Folder found'
    run: npm install  # Assuming you use npm for dependencies (adjust if needed)
    # Run tests (indented under the job)
    name: Run tests (if folder exists)
    if: steps.check-for-folder.outputs == 'Folder found'
    run: |  # Assuming your tests use Playwright test
      npm run test:playwright
      # Or, if your test script is directly named 'test.js'
      # npm run test  # Assuming a test script named 'test.js' exists
