name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Adjust runner OS if needed for your project
    steps:
    - uses: actions/checkout@v3

    - name: Check for folder existence
      id: check-folder
      run: |
        if [ -d "Playwright_API_Automation" ]; then
          echo "Folder found, proceeding with steps"
          echo "::set-output name=folder-exists::true"
        else
          echo "Folder not found, skipping steps"
          echo "::set-output name=folder-exists::false"
          exit 1
        fi

    - name: Install dependencies (if folder exists)
      if: steps.check-folder.outputs.folder-exists == 'true'
      run: |
        cd Playwright_API_Automation
        npm install

    - name: Run tests (if folder exists)
      if: steps.check-folder.outputs.folder-exists == 'true'
      run: |
        cd Playwright_API_Automation
        npm test

