jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for folder existence
        run: |
          if [ -d "Playwright_API_Automation" ]; then
            echo "Folder found, proceeding with steps"
          else
            echo "Folder not found, skipping steps"
            exit 0
          fi
      - name: Install dependencies (if folder exists)
        if: steps.check-for-folder.outputs == 'Folder found'
        run: pip install -r Playwright_API_Automation/requirements.txt  # Assuming requirements are in a file
      - name: Run tests (if folder exists)
        if: steps.check-for-folder.outputs == 'Folder found'
       run: |  # Assuming your tests use playwright test
          npm run test
          # Or, if your test script is directly named 'test.js'
          # npm run test  # Assuming a test script named 'test.js' exists
